### ISSUE TITLE
Should span_id be a parameter of Tracer.start_span()?

### ISSUE THREAD

**Issue by tovin07** [uber/jaeger-client-python#56]
HI,

I see that both jeaeger [1] and basictracer [2] generate ID for new span inside Tracer.start_span().
Which mean that we cannot control the ID from outside.
However, with SpanContext and Span we can put an ID to that.
Therefore, what is the reason for us to make new span ID not controllable?

Currently, my app already had an uuid4 ID for a span. There are 02 options to make uuid4 ID (128 bit) compatibale with OpenTracing ID (usually in 64 bit).
1. Possible easy - Convert uuid 4 to 64 bit ID
2. Impossible - Generate OpenTracing ID from Tracer.start_span() and convert it to uuid4

And, I decide not to use Tracer.start_span, create SpanContext and Span manually :cry:

[1] https://github.com/uber/jaeger-client-python/blob/3315f85e2bcd719b7a5577a73addbf430aea20bb/jaeger_client/tracer.py#L153
[2] https://github.com/opentracing/basictracer-python/blob/master/basictracer/tracer.py#L68

**Comment by yurishkuro** [comment]
What is the origin of your custom span id?

**Comment by tovin07** [comment]
In OpenStack, there is a library with some similar ideas with OpenTracing.
It's OSprofiler, it's ID is UUID4.
I want to make it compatible with OpenTracing => Issue appears.

**Comment by yurishkuro** [comment]
What provides instrumentation of the operations, OSprofiler library or OpenStack itself? Do you have references to its API?

I think it would be better to actually use OpenTracing API as intended. If OSprofiler instrumentation already conceptually similar, it may be possible to write a bridge from its API to OpenTracing API. Then you won't need to hack the implementations of OpenTracing (like Jaeger), the users can simply instantiate any OpenTracing compatible tracer (including Jaeger).

**Comment by tovin07** [comment]
Oh thanks!
I understood your point.

I will ask if I have any other issues :smile:

However, I think that we can control span_id from outside of tracer.start_span() is a good idea (instead of replace span.span_id after create it).
