### ISSUE TITLE
_start_receiving(self):

### ISSUE THREAD

**Issue by yzfshuijing** [uber/jaeger-client-python#66]
i'v read the source code,  in agent.py , there is a method , 
@gen.engine
 def _start_receiving(self):
i can't understand its use , can you explain for me briefly 
thanks so much

**Comment by yurishkuro** [comment]
can you link to the source?

**Comment by black-adder** [comment]
I think you're referring to the thrift autogenerated code? We use it so that our client can talk to agent using thrift over udp.

**Comment by yzfshuijing** [comment]
oh i see, thanks very much
