### ISSUE TITLE
Instructions for running django_opentracing with jaeger

### ISSUE THREAD

**Issue by tanner-bruce** [uber/jaeger-client-python#69]
Instructions for running in a uWSGI, gunicorn and `django runserver` would also be nice.  I should also note that the sample app does not work with the currently released jaeger-client library.

As it stands, simply modifying the django opentracing example to use the jaeger client simply does not work.

**Comment by yurishkuro** [comment]
for uWSGI see https://github.com/uber-common/opentracing-python-instrumentation

**Comment by yurishkuro** [comment]
haven't tried django-opentracing, what doesn't work?

**Comment by tanner-bruce** [comment]
@yurishkuro if you replace the lightstep tracer with the equivalent jaeger tracer inside settings.py the program will hang at `config.initialize_tracer()` when starting via `django runserver` or gunicorn

**Comment by yurishkuro** [comment]
does django fork off children processes?  If so, you need to initialize the tracer in a `@postfork` hook

**Comment by tanner-bruce** [comment]
I believe runserver does. uwsgi definitely does, which I have also tried using along with the uwsgidecorators postfork hook.

I think one of the issues is that the django middleware initializes the tracer at startup, unless the specific setting is set. So, since we init it with @prefork it defaults to using the built in tracer.

I've tried modifying the middleware to use the jaeger tracer by default, but still haven't managed to get it working

**Comment by yurishkuro** [comment]
hm, I wonder how lightstep does it, do they report spans on the main application's thread? Starting a thread before the fork didn't bode well when we were developing jaeger client.

as far as the instrumentation, we typically init the tracer and set it as opentracing.tracer (global var), and instrumentation reads it from there. If django-ot needs the tracer instance at startup, then it probably won't work with Jaeger - it either needs to default to global tracer or accept an accessor function instead of the actual tracer reference.

**Comment by tanner-bruce** [comment]
Alright, we got it running with some modifications to django_opentracing after hearing your suggestions. Thanks!

**Comment by yurishkuro** [comment]
Can you share what you have done, even better maybe do a pull request in django_opentracing to enable Jaeger, not just lightstep?

**Comment by comeaujoseph** [comment]
Unable to get jaeger working with nginx + uwsgi + django. Any suggestions on a fix?

**Comment by megavenik** [comment]
Same issue here:( 

Looks like debugger initializes just before the creation of uwsgi processes, so noone sends any traces at all:(
```
# settings.py
import django_opentracing
import opentracing

# OpenTracing settings

OPENTRACING_TRACE_ALL = True

def tracer():
    from jaeger_client import Config
    print("DEBUGGER BRRRR")
    config = Config(
        config={ # usually read from some yaml config
            'sampler': {
                'type': 'const',
                'param': 1,
            },
            'local_agent': {
                'reporting_host': '127.0.0.1',
                'reporting_port': '5775'
            },
            'logging': True,
        },
        service_name='serv',
        validate=True,
    )
    return config.initialize_tracer()

OPENTRACING_TRACING = django_opentracing.DjangoTracing(tracer())
```

```
DEBUGGER BRRRR
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1fa4830 pid: 1275 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1275)
spawned the uWSGI spooler on dir /var/www/spooler with pid 1280
spawned the uWSGI spooler on dir /var/www/spooler with pid 1281
spawned the uWSGI spooler on dir /var/www/spooler with pid 1282
spawned the uWSGI spooler on dir /var/www/spooler with pid 1283
spawned uWSGI worker 1 (pid: 1284, cores: 1)
spawned uWSGI worker 2 (pid: 1285, cores: 1)
spawned uWSGI worker 3 (pid: 1286, cores: 1)
spawned uWSGI worker 4 (pid: 1287, cores: 1)
spawned uWSGI worker 5 (pid: 1288, cores: 1)
spawned uWSGI worker 6 (pid: 1289, cores: 1)
spawned uWSGI worker 7 (pid: 1290, cores: 1)
spawned uWSGI worker 8 (pid: 1291, cores: 1)
spawned uWSGI worker 9 (pid: 1292, cores: 1)
spawned uWSGI worker 10 (pid: 1293, cores: 1)

```
