### ISSUE TITLE
Support tags injection via JAEGER_TAGS environment variable

### ISSUE THREAD

**Issue by rabbitstack** [uber/jaeger-client-python#74]
For the sake of consistency, it would be useful if tags could be aggregated via `JAEGER_TAGS` environment variable like in the Java client.

**Comment by isaachier** [comment]
Maybe I can do this as part of https://github.com/uber/jaeger-client-python/pull/78.

**Comment by yurishkuro** [comment]
Done in #78

**Comment by rabbitstack** [comment]
Unfortunately, I'm not seeing the desired results when tags are injected via `JAEGER_TAGS` or specified in the tracer config. The tags aren't carried at process-wide basis. If we are seeking to achieve the same consistency as in Java client, the tags should be stored at `Process` level, and not attached as regular tags. Besides that, they should be propagated to each span, not to the root one only.

**Comment by isaachier** [comment]
Look at the test case in test_config.py:

```
def test_tags(self):
        os.environ['JAEGER_TAGS'] = 'a=b,c=d'
        c = Config({'tags': {'e': 'f'}}, service_name='x')
        assert c.tags == {'a': 'b', 'c': 'd', 'e': 'f'}
```

Is that not what you wanted?

**Comment by rabbitstack** [comment]
The tags are injected as expected, actually, the problem is (I suspect that after inspecting the state of the span in Elasticsearch document) related to how tags are propagated / stored in the span storage. Take a look at this document (I exported `JAEGER_TAGS` with `api_token` tag).

```
"tags" : [
           {
             "key" : "sampler.type",
             "type" : "string",
             "value" : "const"
           },
           {
             "key" : "sampler.param",
             "type" : "string",
             "value" : "True"
           },
           {
             "key" : "api-token",
             "type" : "string",
             "value" : "<token>"
           },
           {
             "key" : "pid",
             "type" : "string",
             "value" : "16385"
           },
           {
             "key" : "ppid",
             "type" : "string",
             "value" : "13934"
           },
           {
             "key" : "component",
             "type" : "string",
             "value" : "opentracing-python"
           }
         ],
         "logs" : [ ],
         "processID" : "",
         "process" : {
           "serviceName" : "opentracing-python",
           "tags" : [
             {
               "key" : "hostname",
               "type" : "string",
               "value" : "archrabbit"
             },
             {
               "key" : "ip",
               "type" : "int64",
               "value" : "2130706433"
             },
             {
               "key" : "jaeger.version",
               "type" : "string",
               "value" : "Python-3.6.1"
             }
           ]
         },
```
`api-token` should be stored within `process->tags` and not inside `tags` array (that's at least what Java client is doing). Besides that, `Process` should be propagated to all spans. Only root span is provided with tags injected via JAEGER_TAGS or `tags` attribute.

**Comment by yurishkuro** [comment]
This is the result of python client still using zipkin out of band format. There is no equivalent of "process tags" in zipkin model, so the behavior you're seeing is expected.

**Comment by rabbitstack** [comment]
@yurishkuro Any plans for migrating to native Jaeger format? Are hostname, ip and jaeger.version hardcoded somehow so I'm seeing them despite python client doesn't support process tags?

**Comment by yurishkuro** [comment]
I would like to upgrade python client to jaeger model before Jaeger 1.0 release in December, but we don't have anyone working on it at the moment.

The tracer-level tags are still stored in Zipkin model, but only in the first span of the trace in the given process (we call it "first in process span"), to reduce the overhead of sending them to the backend in every span.
